name: build-frontend-vanguard
run-name: Building Frontend Image for Vanguard Deploy
on:
  workflow_dispatch:

env:
  IMAGE_NAME: rives-frontend

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    environment: Vanguard

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .env
        env:
          DOT_ENV_VARIABLES: >-
            INVITE_CODE_KEY
            NEXT_PUBLIC_ASSETS_BLOCK
            NEXT_PUBLIC_CARTESI_NODE_URL
            NEXT_PUBLIC_CARTRIDGE_CONTRACT
            NEXT_PUBLIC_CONTESTS
            NEXT_PUBLIC_DAPP_ADDR
            NEXT_PUBLIC_GIF_SERVER_URL
            NEXT_PUBLIC_NETWORK_CHAIN_ID
            NEXT_PUBLIC_OPERATOR_ADDR
            NEXT_PUBLIC_TAPE_CONTRACT
            PRIVY_APP_ID
            PRIVY_APP_SECRET
          INVITE_CODE_KEY: ${{ secrets.INVITE_CODE_KEY }}
          NEXT_PUBLIC_ASSETS_BLOCK: ${{ vars.NEXT_PUBLIC_ASSETS_BLOCK }}
          NEXT_PUBLIC_CARTESI_NODE_URL: ${{ vars.NEXT_PUBLIC_CARTESI_NODE_URL }}
          NEXT_PUBLIC_CARTRIDGE_CONTRACT: ${{ vars.NEXT_PUBLIC_CARTRIDGE_CONTRACT }}
          NEXT_PUBLIC_CONTESTS: ${{ vars.NEXT_PUBLIC_CONTESTS }}
          NEXT_PUBLIC_DAPP_ADDR: ${{ vars.NEXT_PUBLIC_DAPP_ADDR }}
          NEXT_PUBLIC_GIF_SERVER_URL: ${{ vars.NEXT_PUBLIC_GIF_SERVER_URL }}
          NEXT_PUBLIC_NETWORK_CHAIN_ID: ${{ vars.NEXT_PUBLIC_NETWORK_CHAIN_ID }}
          NEXT_PUBLIC_OPERATOR_ADDR: ${{ vars.NEXT_PUBLIC_OPERATOR_ADDR }}
          NEXT_PUBLIC_TAPE_CONTRACT: ${{ vars.NEXT_PUBLIC_TAPE_CONTRACT }}
          PRIVY_APP_ID: ${{ vars.PRIVY_APP_ID }}
          PRIVY_APP_SECRET: ${{ secrets.PRIVY_APP_SECRET }}
        run: |
          rm .env
          for var in $DOT_ENV_VARIABLES; do
            echo $var=${!var} >> .env
          done
          echo Final .env:
          cat .env

      - name: Build image
        run: >-
          docker build . --tag $IMAGE_NAME
          --label "runnumber=${GITHUB_RUN_ID}"
          --label "org.opencontainers.image.title=$IMAGE_NAME"
          --label "org.opencontainers.image.description=RIVES Frontend"
          --label "org.opencontainers.image.source=https://github.com/rives-io/rives-frontend"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(git log -1 --format="%at" | xargs -I{} date -d @{} +%Y%m%d.%H%M).$(git rev-parse --short HEAD)-vanguard

          echo Will push $IMAGE_ID:$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
